### ISSUE TITLE
RDS backups are not working

### ISSUE THREAD

**Issue by allaire** [cevoaustralia/aws-backup-lambda#12]
Getting the following error in Cloudwatch logs:

```
Started taking hourly snapshots at 18-04-2018 11:57:15
Finding databases that match the requested tag (
{
    "tag:MakeSnapshot": "True"
}
)
Found 1 databases to manage
Unexpected error: <class 'botocore.errorfactory.DBInstanceNotFoundFault'>
An error occurred (DBInstanceNotFound) when calling the CreateDBSnapshot operation: DBInstance not found: dbinstanceidentifier
Traceback (most recent call last):
File "/var/task/backuplambda.py", line 90, in process_backup
self.snapshot_resource(resource=backup_item, description=description, tags=tags_volume)
File "/var/task/backuplambda.py", line 342, in snapshot_resource
Tags=aws_tagset)
DBInstanceNotFoundFault: An error occurred (DBInstanceNotFound) when calling the CreateDBSnapshot operation: DBInstance not found: dbinstanceidentifier
```

Here's my cloudformation.yml:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple backup process for EC2 and RDS datastores, tag your resources with 'MakeSnapshot' = 'True' (casesensitive) to have snapshots taken and managed
Parameters:
    SuccessSNSTopicOption:
        Description: Supply an either '' (disabled), 'CreateSNS' (build new SNS for this stack), '<sns_arn>' (connect to existing Topic).
        Default: ""
        Type: String
    ErrorSNSTopicOption:
        Description: Supply an either '' (disabled), 'CreateSNS' (build new SNS for this stack), '<sns_arn>' (connect to existing Topic).
        Default: ""
        Type: String

Conditions:
    EnableSuccessSNSTopic: !Not [!Equals [!Ref SuccessSNSTopicOption, ""]] #
    EnableErrorSNSTopic:   !Not [!Equals [!Ref ErrorSNSTopicOption, ""]]

    CreateSuccessSNSTopic: !And                     # We only need to create the Success SNS when it is enabled and not supplied
            - Condition: EnableSuccessSNSTopic
            - !Equals [!Ref SuccessSNSTopicOption, "CreateSNS"]

    CreateErrorSNSTopic:   !And                     # We only need to create the Error SNS when it is enabled and not supplied
            - Condition: EnableErrorSNSTopic
            - !Equals [!Ref ErrorSNSTopicOption,   "CreateSNS"]

Resources:
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "Lambda_execution"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                    - "logs:*"
                Resource: "arn:aws:logs:*:*:*"
        -
          PolicyName: "sns_publish_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                    - "sns:Publish"
                Resource: "*"
        -
          PolicyName: "ec2_snapshot_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                    - "ec2:CreateTags"
                    - "ec2:UpdateTags"
                    - "ec2:DescribeTags"
                    - "ec2:DescribeInstances"
                    - "ec2:CreateSnapshot"
                    - "ec2:DescribeSnapshots"
                    - "ec2:DeleteSnapshot"
                    - "ec2:DescribeVolumes"
                Resource: "*"
        -
          PolicyName: "rds_snapshot_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                    - "rds:DescribeDBInstances"
                    - "rds:DescribeDBSnapshots"
                    - "rds:ListTagsForResource"
                    - "rds:DescribeDBSecurityGroups"
                    - "rds:CreateDBSnapshot"
                    - "rds:DeleteDBSnapshot"
                    - "rds:DescribeDBClusterSnapshots"
                    - "rds:CreateDBClusterSnapshot"
                    - "rds:DeleteDBClusterSnapshot"
                Resource: "*"
  SuccessSNSTopic:
    Type: "AWS::SNS::Topic"
    Condition : CreateSuccessSNSTopic
  ErrorSNSTopic:
    Type: "AWS::SNS::Topic"
    Condition : CreateErrorSNSTopic
  BackupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: backuplambda.lambda_handler
      Runtime: python2.7
      Timeout: 300
      Role: !GetAtt LambdaExecutionRole.Arn
      CodeUri: 'lambda'
      Events:
        DailyBackupEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Input:
              Fn::Join:
              - ''
              - - '{"period_label": "day", "period_format": "%a%H-%M", "keep_count": 14,'
                - '"arn": "'
                - !If [EnableSuccessSNSTopic, !If [ CreateSuccessSNSTopic, Ref: SuccessSNSTopic, Ref: SuccessSNSTopicOption], '']
                - '", '
                - '"error_arn": "'
                - !If [EnableErrorSNSTopic, !If [ CreateErrorSNSTopic, Ref: ErrorSNSTopic, Ref: ErrorSNSTopicOption], '']
                - '", '
                - '"ec2_region_name": "'
                - Ref: AWS::Region
                - '", '
                - '"rds_region_name": "'
                - Ref: AWS::Region
                - '", '
                - '"tag_name": "MakeSnapshot", "tag_value": "True" }'
        WeeklyBackupEvent:
          Type: Schedule
          Properties:
            Schedule: rate(7 days)
            Input:
              Fn::Join:
              - ''
              - - '{"period_label": "week", "period_format": "%U", "keep_count": 12,'
                - '"arn": "'
                - !If [EnableSuccessSNSTopic, !If [ CreateSuccessSNSTopic, Ref: SuccessSNSTopic, Ref: SuccessSNSTopicOption], '']
                - '", '
                - '"error_arn": "'
                - !If [EnableErrorSNSTopic, !If [ CreateErrorSNSTopic, Ref: ErrorSNSTopic, Ref: ErrorSNSTopicOption], '']
                - '", '
                - '"ec2_region_name": "'
                - Ref: AWS::Region
                - '", '
                - '"rds_region_name": "'
                - Ref: AWS::Region
                - '", '
                - '"tag_name": "MakeSnapshot", "tag_value": "True" }'
        HourlyBackupEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Input:
              Fn::Join:
              - ''
              - - '{"period_label": "hourly", "period_format": "%a%H-%M", "keep_count": 24,'
                - '"arn": "'
                - !If [EnableSuccessSNSTopic, !If [ CreateSuccessSNSTopic, Ref: SuccessSNSTopic, Ref: SuccessSNSTopicOption], '']
                - '", '
                - '"error_arn": "'
                - !If [EnableErrorSNSTopic, !If [ CreateErrorSNSTopic, Ref: ErrorSNSTopic, Ref: ErrorSNSTopicOption], '']
                - '", '
                - '"ec2_region_name": "'
                - Ref: AWS::Region
                - '", '
                - '"rds_region_name": "'
                - Ref: AWS::Region
                - '", '
                - '"tag_name": "MakeSnapshot", "tag_value": "True" }'
```

**Comment by allaire** [comment]
So I just re-deployed my cloudformation stack but with the `backuplambda.py` prior to #8 (https://github.com/cevoaustralia/aws-backup-lambda/tree/de8796013fe2957035d8c4d3d7738404a79e595a) and my RDS backups are now working. I think #8 might have been merged too soon without much tests.

cc @wobeng @stevemac007

**Comment by wobeng** [comment]
hmm https://github.com/wobeng/aws-backup-lambda worked well for me...what is your current db setup?

**Comment by allaire** [comment]
1x RDS Postgresql Multi-AZ, no clusters.

**Comment by allaire** [comment]
I suppose you use cluster, and might have broke the regular use case

**Comment by wobeng** [comment]
I'm going to test it later tonight

Do you have the main RDS tagged?

**Comment by allaire** [comment]
Yes, AFAIK you can't tag the Multi-AZ database (it's managed by AWS under the hood).

You can take a look at my stacktrace in my first post and see that the script finds my tagged database correctly.

**Comment by wobeng** [comment]
See attached. Do you have it tagged

![image](https://user-images.githubusercontent.com/11966846/38935851-5bbbfc2c-42ed-11e8-9d72-573ba0ecbce1.png)

**Comment by allaire** [comment]
Yes I do, see my stack in my first post (‘Found 1 databases to manage‘)

**Comment by wobeng** [comment]
ahh got...will test without cluster to see. I only provided an update to the code for cluster and tested it. I assumed without cluster always worked

**Comment by allaire** [comment]
Yeah, maybe a small regression somewhere, since it works prior to your commit. Since I don't need cluster support it's fine with me, but we should fix what's on master I think :)

**Comment by wobeng** [comment]
I agree...both with cluster and non-cluster should work. This is a great tool

**Comment by danmoz** [comment]
I think I found the issue, just posted PR #13

**Comment by stevemac007** [comment]
That looks like a great fix - are you willing to raise a pull-request to merge this change back?

**Comment by stevemac007** [comment]
This change has been merged and looks to fix the issue - please reopen this issue if the problems still persist.
