### ISSUE TITLE
An error occurred (InvalidParameterValue) when calling the CreateDBSnapshot operation

### ISSUE THREAD

**Issue by wobeng** [cevoaustralia/aws-backup-lambda#5]
`Unexpected error: <class 'botocore.exceptions.ClientError'>
An error occurred (InvalidParameterValue) when calling the CreateDBSnapshot operation: The specified instance is a member of a cluster and a snapshot cannot be created directly. Please use the CreateDBClusterSnapshot API instead.
Traceback (most recent call last):
  File "/var/task/backuplambda.py", line 89, in process_backup
    self.snapshot_resource(resource=backup_item, description=description, tags=tags_volume)
  File "/var/task/backuplambda.py", line 329, in snapshot_resource
    Tags=aws_tagset)
ClientError: An error occurred (InvalidParameterValue) when calling the CreateDBSnapshot operation: The specified instance is a member of a cluster and a snapshot cannot be created directly. Please use the CreateDBClusterSnapshot API instead.`

**Comment by wobeng** [comment]
fixed in #8
